import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Main from '../components/Main'
import About from '../components/About'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import Resume from '../components/Resume'
import Footer from '../components/Footer'
import ScrollTop from '../components/ScrollTop'


export default function Home() {
  return (
  <div>
    <Head>
      <title>Pawan Patil</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/faviconpkp.png" />
    </Head>
    <Navbar />
    <Main />
    <About />
    <Projects />
    <Skills />
    <Resume />
    <Footer />
    <ScrollTop/>
    
  </div>
  
  )
}
